inputs = {
  ci-custom_vendor-data_source_raw_data = <<-EOF
    #cloud-config

    final_message: |
      cloud-init has finished
      version: $version
      timestamp: $timestamp
      datasource: $datasource
      uptime: $uptime

    keyboard:
      layout: us

    locale: C.UTF-8

    ntp:
      enabled: true
      ntp_client: chrony

    package_reboot_if_required: true
    package_update: true
    package_upgrade: true
    packages:
      - qemu-guest-agent
      - rng-tools5

    runcmd:
      - systemctl enable qemu-guest-agent
      - systemctl start qemu-guest-agent
      - systemctl enable rngd
      - systemctl start rngd
      - update-grub

    random_seed:
      command: ["sh", "-c", "dd if=/dev/urandom of=/var/lib/cloud/random-seed bs=512 count=1"]
      command_required: true
      encoding: raw

    timezone: Europe/Moscow

    write_files:
    - path: /etc/default/grub.d/99-cloudimg-settings.cfg
      content: |
               # This file was generated by cloud-init, based on custom vendor-data file from proxmox
               GRUB_TIMEOUT_STYLE=menu
               GRUB_TIMEOUT=5
      owner: 'root:root'
      permissions: '0644'
      defer: true
    - path: /etc/default/rng-tools
      content: |
               # This file was generated by cloud-init, based on custom vendor-data file from proxmox
               HRNGDEVICE=/dev/hwrng
      owner: 'root:root'
      permissions: '0644'
      defer: true
    
    EOF
}
